name: aoc_2023
description: A sample command-line application.
version: 23.12.4
publish_to: 'none'

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  collection: ^1.18.0

dev_dependencies:
  build_runner: ^2.4.7
  lints: ^3.0.0
  test: ^1.24.9
